### ISSUE TITLE
Redenering voor URI van eigenschap bemonsterdObject van klasse Verkeersbemonsteringsobject

### ISSUE THREAD

**Issue by ddvlanck** [Informatievlaanderen/OSLOthema-verkeersmetingen#11]
De toegekende URI van de eigenschap `bemonsterdObject` is een nieuwe URI binnen het domein verkeersmetingen, namelijk `https://data.vlaanderen.be/ns/verkeersmetingen#bemonsterdObject`. 

De naam van het domein van deze eigenschap, `Verkeersbemonsteringsobject`, geeft het al wat weg, maar waarom is dit geen subklasse van `Bemonsteringsobject`, zoals gedefinieerd in het [applicatieprofiel 'Sensoren en Bemonstering'](https://data.vlaanderen.be/doc/applicatieprofiel/sensoren-en-bemonstering/kandidaatstandaard/2022-04-28/#Bemonsteringsobject)? Op deze klasse staat ook een eigenschap `bemonsterdObject` gedefinieerd, met een URI die hergebruikt uit een andere standaard, namelijk `http://def.isotc211.org/iso19156/2011/SamplingFeature#SF_SamplingFeature.sampledFeature`.

**Comment by yarondassonneville** [comment]
Bedankt voor de melding van dit issue. Dit werd aangepast.
