### ISSUE TITLE
Redenering URI's eigenschappen klasse Verkeersmetingverzameling

### ISSUE THREAD

**Issue by ddvlanck** [Informatievlaanderen/OSLOthema-verkeersmetingen#12]
In het applicatieprofiel staat deze klasse gedefinieerd als een subklasse van `Observatieverzameling`, die werd overgenomen uit het [applicatieprofiel "Sensoren en Bemonstering"](https://data.vlaanderen.be/doc/applicatieprofiel/sensoren-en-bemonstering/#Observatieverzameling).

Dat betekent dat alle eigenschappen van die klasse automatisch worden overgeërfd door de klasse `Verkeersmetingverzameling`. Waarom worden de eigenschappen (`fenomeentijd`, `geobserveerdKenmerk`, `geobserveerdObject`, `uitgevoerdMet`) dan opnieuw gedefinieerd (nieuwe URI binnen het domein verkeersmetingen)?

**Comment by yarondassonneville** [comment]
Bedankt voor de melding. De wijzigingen hiervoor zijn doorgevoerd.
