### ISSUE TITLE
URI van eigenschap waardeverschaffer van klasse Verkeersobject

### ISSUE THREAD

**Issue by ddvlanck** [Informatievlaanderen/OSLOthema-verkeersmetingen#13]
De klasse `Verkeersobject` is een subklasse van de klasse `Object`. Deze klasse werd overgenomen uit het [applicatieprofiel 'Observaties en Metingen'](https://data.vlaanderen.be/doc/applicatieprofiel/observaties-en-metingen/kandidaatstandaard/2022-04-28/#Object), waarin reeds een URI voor de eigenschap `waardeverschaffer` werd toegekend.

Waarom wordt deze eigenschap opnieuw gedefinieerd (nieuwe URI, namelijk `https://data.vlaanderen.be/ns/verkeersmetingen#waardeverschaffer`) binnen het domein verkeersmetingen en wordt niet de reeds bestaande definitie (URI) overgenomen?

**Comment by yarondassonneville** [comment]
Bedankt voor de melding van dit issue. De toelichting hierrond kan teruggevonden worden in het verslag van de vijfde thematische werkgroep.

Korte samenvatting:
- Specialisatie omdat een verkeersobject / bemonsterdobject eender wat zou kunnen zijn (bv. Een gebouw). ​
- We willen dit strict houden, dus zijn URI's aangepast.​
- De relatie zit op een hoger niveau en is gespecialiseerd waardoor deze niet overerft.
