### ISSUE TITLE
Voorstel aanpassing 

### ISSUE THREAD

**Issue by samuvack** [Informatievlaanderen/OSLOthema-verkeersmetingen#15]
Momenteel is het verwachte type "[LineaireReferentie](https://data.vlaanderen.be/doc/applicatieprofiel/verkeersmetingen/#LineaireReferentie)" van de eigenschap netwerkreferentie van de klasse Rijrichting:

![image](https://github.com/Informatievlaanderen/OSLOthema-verkeersmetingen/assets/15192194/feb37e8a-3253-4210-afe1-1c16e3f42715)

Voorstel hierbij is om alsook Netwerkelement
https://data.vlaanderen.be/ns/netwerk/#Netwerkelement
toe te laten als verwacht type, zodat het wegsegment kan toegevoegd worden onder netwerkreferentie.

**Comment by GeertThijs** [comment]
Is aangepast
