### ISSUE TITLE
Titels van eigenschappen zorgen voor verwarring

### ISSUE THREAD

**Issue by samuvack** [Informatievlaanderen/OSLOthema-verkeersmetingen#4]
Bij externen die gebruik maken van https://data.vlaanderen.be/ns/verkeersmetingen/
zorgen de titels bij de eigenschappen voor verwarring:

Bijvoorbeeld https://data.vlaanderen.be/ns/verkeersmetingen/#^bemonsterdObject zou ik aanpassen naar 
"Eigenschap bemonsterdObject"

**Comment by yarondassonneville** [comment]
Dag Samuel

Bedankt voor de terechte opmerking. We hebben deze aspecten aangepast in de specificatie.

Met vriendelijke groeten
Yaron
