### ISSUE TITLE
Wrong URI for ObservatieProcedure

### ISSUE THREAD

**Issue by ddvlanck** [Informatievlaanderen/OSLOthema-verkeersmetingen#8]
The assigned URI is `https://www.w3.org/TR/vocab-ssn/#SOSAProcedure`, which is an anchor in the specification page. The actual URI is `http://www.w3.org/ns/sosa/Procedure`.

**Comment by yarondassonneville** [comment]
Thank you for providing this feedback. This issue has been resolved.
