### ISSUE TITLE
Wrong URI for Observatieverzameling

### ISSUE THREAD

**Issue by ddvlanck** [Informatievlaanderen/OSLOthema-verkeersmetingen#9]
The assigned URI is `https://www.w3.org/TR/vocab-ssn-ext/#sosa:ObservationCollection`, which leads to an anchor in the specification page. The actual URI should be `http://www.w3.org/ns/sosa/ObservationCollection`.

**Comment by yarondassonneville** [comment]
Thank you for providing this feedback. This issue has been resolved.
